### ISSUE TITLE
Accept unquoted or remaining arguments as the shell command

### ISSUE THREAD

**Issue by xlucn** [endaaman/tym#101]
I tested these scenarios with nemo, with the following gsettings:
```
$ gsettings get org.cinnamon.desktop.default-applications.terminal exec
'tym'
$ gsettings get org.cinnamon.desktop.default-applications.terminal exec-arg
'--'
```

1. "Open with" -> "Neovim" on text files does not open the text file, only a empty buffer.
2. "Open in terminal" does not open tym in the current folder, but the folder the daemon started in. This only applies when tym is in daemon mode.

I am not sure if these problems can be worked around by changing the gsetting options. Otherwise, it must have something do with tym itself.

**Comment by js-everts** [comment]
1. Shouldn't `gsettings get org.cinnamon.desktop.default-applications.terminal exec-arg` be set to `-e`. But even then I'm not sure this will work as expected because of how `tym` expects args for the `-e` flag.  I have a hacky partial fix implemented [here](https://github.com/js-everts/tym/tree/prog_args) that you can test.

2. Make sure you have the latest version and the latest daemon is running to open terminals in the current folder.

**Comment by xlucn** [comment]
@js-everts Thank you for the reply! Problems basically solved.

1. I did notice the `-e` flag, and also the fact that the shell command need quoting. As tested, the flag change doesn't work. But your fix branch works!
2. Indeed it's because I haven't restarted the daemon since v3.4.1 update, this version works well now.

**Comment by js-everts** [comment]
Just for completeness, I should mention my fix won't work if you try to open a file with spaces in it.

**Comment by xlucn** [comment]
I noticed. I looked into your fix's code, and saw the comment `It would be much better if can store these as an array`. That will indeed solve that issue.

**Comment by endaaman** [comment]
Sorry for late reply.

As you note, tym can not handle the options correctly. In this case, I think it is appropreate to use double dash option ( `--` ).

For example in lxc, 

```
$ lxc exec <container name> ls -l /usr
```

This won't work but

```
$ lxc exec <container name> -- ls -l /usr
```

This works. The options after `--` is ignored by `lxc` command and they are processed together. As a UNIX command, this treatment traditionally exists. I guess the DE (cinnamon) also expects the treatment implicitly.

To implement this, I need some time to find _the correct behavior as a normal terminal_ but I will do in due time. Please wait.

**Comment by js-everts** [comment]
@endaaman 

For what its worth you can find my take on this [here](https://github.com/js-everts/tym/tree/commands). It basically follows your idea of using `--` followed by commands:

```
$ tym -- less Dockerfile
```
While all this works (both in --isolated and --daemon). Lua can no longer set the command ('shell'). Since all the lua config fields and command line options come from the same table and since I have removed the '--shell' flag from that table, Lua no longer has knowledge about it. I'm not sure how to go about this (maybe special case 'commands'?). 

Anyway, I think we would want something like this in lua word:
```
tym.set('command', {'prog', 'arg1', 'arg2'})

tym.setconfig({
    'command', {'prog', 'arg1', 'arg2'},
})

// or maybe even
tym.set_command({'prog', 'arg1', 'arg2'})
```

**Comment by xlucn** [comment]
I changed the issue title, since this is the main problem here. Feel free to improve it to better describe the issue.

Basically, tym could fit into more scenarios (including some gui file managers) if it accepts shell command options as some other programs, like st, alacritty or foot, do:
- Accepts all remaining arguments, those tym does not accept, as shell command, i.e.
  `tym [tym options] command [command args]`
- For compatibility, accept a `-e` option, i.e.
  `tym [tym options] -e command [command args]`
  This effectively makes `-e` the last option since anything after it is treated as shell command.

**Comment by endaaman** [comment]
The spec "Only when `-e` is provided, the following options are parsed differently" is a kind of the workarounds, I think.
I feel that this kind of issues are equally problematic in other projects and that the general consensus is to use `--`.

**Comment by xlucn** [comment]
I think, which solution to choose really depends on the way of how other popular programs spawn terminal emulators. For example, tym has to work with most file managers on opening terminal in current directory and open text files with vim in a terminal, etc. So, to know whether they support `--` maybe require some research.
