### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by TimothyDespair** [endaaman/tym#31]
First off thanks for writing this, it's brilliant!

It's made my life so much easier keeping configs in sync with Awesome and Luakit. Managing configs has been a dream!

I was wondering how hard it would be to implement padding around all 4 edges of the terminal. I may submit a pull request myself for this but I'm not very experienced with C programming (plenty of experience in other languages though.) If you point me in the right direction I might be able to hack it together in the next few days and submit a PR.

Thanks again!

Tim

**Comment by endaaman** [comment]
Hello @TimothyDespair ,

I am very happy to hear that you liked it. And thanks for a good suggestion.

It is not hard to implement so I did a padding feature on [feature/padding branch](https://github.com/endaaman/tym/tree/feature/padding) as a trial, how do you think about this?

![screenshot at 2018-11-10 18-56-23](https://user-images.githubusercontent.com/2020942/48300079-58693380-e51a-11e8-9dff-afbe53c1cb32.png)

**Comment by endaaman** [comment]
(And we need to add the config value for the color of the padded part (e.g. `window_backgroud_color`) and implement drawing.)

**Comment by TimothyDespair** [comment]
Brilliant! Such a quick turn-around! I only just got around to installing the branch, looks great!

**Comment by endaaman** [comment]
The feature has been added on master branch. This time I implemented it but I hope you will submit PR  next time.

The commit 4fa998454e2dae4260446728dcb2f5090afa168f has a lot of important points for adding a feature.

1. Add config definition: Specifing the name, default value, type, description and etc. https://github.com/endaaman/tym/commit/4fa998454e2dae4260446728dcb2f5090afa168f#diff-75218e1e64b8201a55c2ac2203e8970cR92

2. Implement the function: This time, setting the padding to the elements https://github.com/endaaman/tym/commit/4fa998454e2dae4260446728dcb2f5090afa168f#diff-b6d675c6fe3e33e1f3daf8bfdc15f45cR108

3. Write docs on `README.md` and `tym.1.in`

(Background painting might be a bit complicated because of circumstances specific to GTK+ though...)

And what I have to tell you in addition is that you don't have to install the app to test and develop `tym`. My development flow is like the following.

1. Clone the repository
2. Run `$ autoreconf -fvi`
3. Run `$ ./configure --enable-debug` (and you can get some informative logs.)
4. Run `$ make && ./src/tym -e /path/to/config-for-dev.lua`
5. Write some codes.
6. And back to `4.`

PR is always welcome. Thank you!
