### ISSUE TITLE
Add config option to disable bell

### ISSUE THREAD

**Issue by iTakeshi** [endaaman/tym#39]
I want to disable audible bell through config, like:
```lua
tym.set_config({
    audible_bell = false,
})
```

Also, it should be independent from "urgent on bell" functionality #21 (i.e. I want to disable bell sound but the window should become urgent if a bell character is issued)

**Comment by endaaman** [comment]
I added the config option `silent` at commit 0f340d4d9de233cb8ab70e3168dea4e6423e1b51

The option was named not `audible` but `silent` because when to try set custom value via command-line option the form like `--audible-bell=false` is ugly and `--slient` seems smart.

You can check it on HEAD of master branch.

**Comment by iTakeshi** [comment]
I just tested this, but it seems confusing that the bell rings IF SILENT IS TRUE. Shouldn't it be opposite?

**Comment by iTakeshi** [comment]
LGTM :+1: 
closing, thanks!
