### ISSUE TITLE
Transparency in current version?

### ISSUE THREAD

**Issue by demonbob** [endaaman/tym#42]
Hey guys, 

Is there anyway to do transparency in the current version?

**Comment by endaaman** [comment]
Hello @demonbob 

I think that is good idea but , unfortunately it is difficult. `tym` is using [VTE](https://developer.gnome.org/vte/unstable/) and VTE does not have option of transparent **now**.

The reason to emphasize **now** is that the option existed in the past but it was removed until today. See the following page. 

https://developer.gnome.org/vte/0.36/VteTerminal.html#vte-terminal-set-background-transparent

Function `vte_terminal_set_background_transparent()` was deprecated at version `0.36`. And the function was removed at version `0.38`. There is no option for transparency in VTE. 

If you were a GNOME Terminal user for some years, you probably saw the option of "Window transparency" and realized the option disappeared one day. The reason is that I said above.

I thought the transparent feature is desirable and I tried to implement it but I finally gave up it.

**Comment by endaaman** [comment]
@demonbob 

I added the `'transparent'` option at the commit 6e495b0d898ae6e91ce12576efc876c6697997a5 . If the option is set `true`, the background of the terminal widget will not be drawn. Therefore the background color is one of your GTK theme  not `color_background`. And now we can use transparent color for the background color of the window, so we can transmit the window.

```lua
tym.set_config({
  padding_horizontal = 30,
})
```

![Screenshot at 2019-07-28 21-24-51](https://user-images.githubusercontent.com/2020942/62006630-29652180-b17e-11e9-8681-0de19fd38638.png)

↑ GTK theme color is used on the padded area.

----

```lua
tym.set_config({
  padding_horizontal = 30,
  color_window_background = 'rgba(1.0, 1.0, 1.0, 0.5)',
})
```

![Screenshot at 2019-07-28 21-09-29](https://user-images.githubusercontent.com/2020942/62006538-95468a80-b17c-11e9-8458-348810846ae1.png)

↑ The padded area is transparent.

----

```lua
tym.set_config({
  transparent = true,
  color_window_background = 'rgba(1.0, 1.0, 1.0, 0.5)',
})
```

![Screenshot at 2019-07-28 21-28-15](https://user-images.githubusercontent.com/2020942/62006660-a7292d00-b17e-11e9-95db-c9e9eb12d254.png)

↑ The window is transparent. No padded. This is what we wanted.


Please be careful about  color specification method. You need to write such as `rgba (1.0, 1.0, 1.0, 0.5)` because [gdk_rgba_parse()](https://developer.gnome.org/gdk3/stable/gdk3-RGBA-Colors.html#gdk-rgba-parse) is used as the parser.

And the specification of options is just experimental. It may change in the future.

**Comment by endaaman** [comment]
Now window transparency has been supported. See the section Transparent window of Tips in `README.md`.
