### ISSUE TITLE
tym.send_key('<Ctrl>m') not working?

### ISSUE THREAD

**Issue by vstath** [endaaman/tym#47]
Can someone provide any ideas why this is not working
  tym.send_key('< Ctrl >m')
while 
  tym.send_key('KP_Enter')
works fine?

Is there something that prohibits the CTRL-M? Works fine if I manually send it, etc. I'm confused since I think it used to work in some of my initial tests. 

Any feedback welcome!

**Comment by vstath** [comment]
I just realized that if focus is on the terminal window then <Ctrl>m does not seem to work. If I switch focus on another window then it works fine !?!?!?

**Comment by endaaman** [comment]
Can you show me your machine environment (OS, desktop env, window manager etc...) and the minimal config Lua code to reproduce the situation?

The following code seems to work correctly for me on my env.

```lua
local tym = require 'tym'

tym.set('shell', 'sh')

tym.set_timeout(function()
  tym.send_key('<Ctrl>m')
  return true
end, 1000)
```

My machine info:
-  Arch Linux
- MATE
- Marco

**Comment by vstath** [comment]
I am using i3wm in Linux Mint 19.1 Tessa

When focus is on another window the code above works fine and presses enter every second. When focus is on the terminal window then it does not work :-) 

It's very weird but probably is an i3wm issue? I will look into it from that angle.

**Comment by endaaman** [comment]
```lua
local tym = require 'tym'

tym.set('shell', 'sh')

tym.set_timeout(function()
  -- tym.send_key('<Ctrl>m')
  print('hoge')
  return true
end, 1000)
```

Is above code work correctly (logs will be printed) when the window has focus? Please launch tym from command line like `$ tym -u /path/to/config.lua` and confirm it.

If it works, it follows that the problem comes from `set_timeout()` not from `send_key()`. I have never used i3 so I want you to check it.

**Comment by vstath** [comment]
Ok, let me explain the setup. 

i3 windows manager has hotkeys (the most prominent one to start a terminal). So typically the mod key is Alt or Super. 

My combination is Super+t to start a terminal. 

Now, if I run tym within the default i3 terminal, it works fine (so tym terminal executed within i3 default terminal let's say). The "hoge" is printed etc. But when I press Super+t (ie tym starts on its own window as a standalone application) then "hoge" is not printed, even if focus goes to another window. 

Naturally, I would like to use tym as my default terminal (and script it and automate it in my favorite Lua). Perhaps that's not the intended way of using it? Should tym run from another terminal???

I will try to make a video and demonstrate.

**Comment by vstath** [comment]
Let me verify first with i3 people because xdotools does not send keys to another window so it may be related.

**Comment by endaaman** [comment]
Just for testing I asked to launch from command line. You can use tym same as any other terminals.

When you have a problem using my first code, we can't aware whether `set_timeout()` or `send_key()` causes the problem. So if you launch tym from another terminal and see logs whether active or inactive, it follows that `send_key()` causes it and `set_timeout()` is not broken. But when you launch tym by pressing shortcut key or clicking a desktop entry file such as `tym.desktop` you can't see logs, so you need to launch tym from command line.
 
If the problem comes from `send_key()`, It is definitely related to the behavior of xdotools. It is good to verify with them.

**Comment by endaaman** [comment]
At least either  `tym.send_key('<Ctrl>m')`  or `tym.send_key('KP_Enter')` works.
