### ISSUE TITLE
theme.lua colors

### ISSUE THREAD

**Issue by vstath** [endaaman/tym#56]
Perhaps in the documentation we should offer sample xterm 256 colors?

From https://jonasjacek.github.io/colors/

```local fg = '#d2d4de'
local bg = '#000000'
return {
  color_background = bg,
  color_foreground = fg,
  color_0  = '#000000',
  color_1  = '#800000',
  color_2  = '#008000',
  color_3  = '#808000',
  color_4  = '#000080',
  color_5  = '#800080',
  color_6  = '#008080',
  color_7  = '#c0c0c0',
  color_8  = '#808080',
  color_9  = '#ff0000',
  color_10  = '#00ff00',
  color_11  = '#ffff00',
  color_12  = '#0000ff',
  color_13  = '#ff00ff',
  color_14  = '#00ffff',
  color_15  = '#ffffff',
}
```

The master HEAD has changes compared to previous versions and the default colours have changed. Might be useful to provide the above as a default sample in the README.md

This link might be useful as well for visual customization of the theme: https://terminal.sexy/

**Comment by endaaman** [comment]
I have updated README. The color mapping is shown in the `Color correspondence` section. It is to be clicked to open and close.

The default theme color is [iceberg](https://cocopon.github.io/iceberg.vim/) now, which is my personal favorite color scheme. I think the theme that you showed is never used as it is, because it is not optimized in terms of design and productivity and  tym users should be some core geeks. So rather than adopting a theme that is never used, it is better to adapt as default to my most recommended theme.
