### ISSUE TITLE
bump lua version

### ISSUE THREAD

**Issue by TorchedSammy** [endaaman/tym#67]
currently building on fedora takes a tiny bit of extra effort since lua in fedora 35 is 5.4 and not 5.3
i had to change lua53 in the configure to lua, so maybe you could push that also?
or is there another way to fix this, i dont know much about stuff involving c

**Comment by endaaman** [comment]
@TorchedSammy 

fad27053037e537bca61da9b8b4a42d4907c8335

I specified lua version as `lua5.3` because Ubuntu's lua package provides only `lua5.3` entry but does not `lua`.

I searched about `PKG_CHECK_MODULES()` again and found the way to set the condition, then it worked.
So now you never think about lua version stuffs.

**Comment by TorchedSammy** [comment]
ok that works thanks!
